import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useAuth } from '../context/AuthContext'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import Button from '../components/ui/Button'
import { Check, X, Scale } from '../components/icons/Icons'

const plans = [
  {
    name: 'Free',
    price: '$0',
    period: '',
    desc: 'For individuals exploring the platform',
    features: [
      { label: '3 contract previews / month', included: true },
      { label: 'All 8 contract types', included: true },
      { label: 'All 13 jurisdictions', included: true },
      { label: 'Quebec Civil Code support', included: true },
      { label: 'Watermarked drafts', included: true },
      { label: 'PDF / Word export', included: false },
      { label: 'Remove watermark', included: false },
      { label: 'Priority support', included: false },
    ],
    cta: 'Start Free',
    href: '/signup',
    highlight: false,
  },
  {
    name: 'Starter',
    price: '$30',
    period: '/month CAD',
    desc: 'For freelancers and independent professionals',
    features: [
      { label: '20 contracts / month', included: true },
      { label: 'All 8 contract types', included: true },
      { label: 'All 13 jurisdictions', included: true },
      { label: 'No watermark', included: true },
      { label: 'PDF + Word export', included: true },
    ],
    cta: 'Start Starter',
    href: '/checkout/starter',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$80',
    period: '/month CAD',
    desc: 'For businesses and legal teams',
    features: [
      { label: 'Unlimited contracts', included: true },
      { label: 'All 8 contract types', included: true },
      { label: 'All 13 jurisdictions', included: true },
      { label: 'No watermark', included: true },
      { label: 'PDF + Word export', included: true },
      { label: 'Priority support', included: true },
      { label: 'Team collaboration (coming soon)', included: true },
    ],
    cta: 'Start Pro',
    href: '/checkout/pro',
    highlight: true,
  },
]

const faq = [
  {
    q: 'Is LegalAI a law firm?',
    a: 'No. LegalAI is a software platform that generates contract drafts based on Canadian law. We are not a law firm and do not provide legal advice. Always have contracts reviewed by a qualified lawyer before signing.',
  },
  {
    q: 'Are the contracts legally binding?',
    a: 'Contracts generated by LegalAI are based on standard Canadian legal provisions. However, all contracts should be reviewed by a licensed lawyer before use. Legal bindingness depends on proper execution and the specific facts of your situation.',
  },
  {
    q: 'Does the Free plan really cover all 13 jurisdictions?',
    a: 'Yes. All plans, including Free, support all 13 Canadian provinces and territories, including Quebec\'s Civil Code framework. Plan differences are in export capability, watermarks, and contract volume.',
  },
  {
    q: 'Can I cancel anytime?',
    a: 'Yes, all paid plans can be cancelled at any time. Your plan remains active until the end of the current billing period.',
  },
  {
    q: 'What happens to my contracts if I downgrade?',
    a: 'Your contracts are always accessible. Downgrading to Free means new contracts will have watermarks and export is disabled. Existing saved contracts remain in your dashboard.',
  },
]

export default function Pricing() {
  const { user, profile } = useAuth()

  return (
    <div className="min-h-screen bg-navy font-sans flex flex-col">
      <Navbar />

      <main className="flex-1">
        {/* Header */}
        <section className="pt-32 pb-16 px-6 text-center">
          <div className="max-w-2xl mx-auto">
            <p className="text-xs uppercase tracking-luxury text-bronze mb-4">Pricing</p>
            <h1 className="font-serif text-5xl text-white mb-4">Simple, Transparent Plans</h1>
            <p className="text-gray-500 text-lg">
              All prices in Canadian dollars. No hidden fees. Cancel anytime.
            </p>
          </div>
        </section>

        {/* Plans */}
        <section className="pb-20 px-6">
          <div className="max-w-5xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {plans.map((plan, i) => {
                const isCurrent = profile?.plan === plan.name.toLowerCase()
                return (
                  <motion.div
                    key={plan.name}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: i * 0.1 }}
                    className={`relative rounded-lg p-6 flex flex-col ${
                      plan.highlight
                        ? 'bg-navy-700 border-2 border-bronze'
                        : 'bg-navy-700 border border-white/5'
                    }`}
                  >
                    {plan.highlight && (
                      <div className="absolute -top-3.5 left-1/2 -translate-x-1/2">
                        <span className="bg-bronze text-navy text-[10px] font-bold tracking-luxury uppercase px-4 py-1 rounded-full">
                          Most Popular
                        </span>
                      </div>
                    )}

                    <div className="mb-6">
                      <h3 className="text-xs uppercase tracking-luxury text-gray-400 mb-2">{plan.name}</h3>
                      <div className="flex items-baseline gap-1 mb-2">
                        <span className="font-serif text-5xl text-white">{plan.price}</span>
                        {plan.period && <span className="text-sm text-gray-500 ml-1">{plan.period}</span>}
                      </div>
                      <p className="text-sm text-gray-500">{plan.desc}</p>
                    </div>

                    <ul className="space-y-3 mb-8 flex-1">
                      {plan.features.map(f => (
                        <li key={f.label} className="flex items-start gap-2.5 text-sm">
                          {f.included ? (
                            <Check size={14} className="text-bronze flex-shrink-0 mt-0.5" />
                          ) : (
                            <X size={14} className="text-gray-700 flex-shrink-0 mt-0.5" />
                          )}
                          <span className={f.included ? 'text-gray-300' : 'text-gray-700'}>{f.label}</span>
                        </li>
                      ))}
                    </ul>

                    {isCurrent ? (
                      <Button variant="ghost" className="w-full cursor-default" disabled>
                        Current Plan
                      </Button>
                    ) : (
                      <Link to={user ? plan.href : '/signup'}>
                        <Button variant={plan.highlight ? 'primary' : 'outline'} className="w-full">
                          {plan.cta}
                        </Button>
                      </Link>
                    )}
                  </motion.div>
                )
              })}
            </div>

            <p className="text-center text-xs text-gray-600 mt-6">
              All plans include access to LegalAI's full contract library. GST/HST applies where applicable.
            </p>
          </div>
        </section>

        {/* FAQ */}
        <section className="py-20 border-t border-white/5 px-6">
          <div className="max-w-2xl mx-auto">
            <p className="text-xs uppercase tracking-luxury text-bronze text-center mb-3">FAQ</p>
            <h2 className="font-serif text-3xl text-white text-center mb-10">Common Questions</h2>
            <div className="space-y-6">
              {faq.map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: i * 0.05 }}
                  viewport={{ once: true }}
                  className="border-b border-white/5 pb-6"
                >
                  <h3 className="font-medium text-white mb-2 text-sm">{item.q}</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">{item.a}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 border-t border-white/5 px-6 text-center">
          <Scale size={32} className="text-bronze mx-auto mb-6" strokeWidth={1} />
          <h2 className="font-serif text-3xl text-white mb-4">Ready to Draft Your First Contract?</h2>
          <p className="text-gray-500 mb-8 text-sm">No credit card required for the Free plan.</p>
          <Link to="/signup">
            <Button size="lg">Start for Free</Button>
          </Link>
        </section>
      </main>

      <Footer />
    </div>
  )
}
